title:       Adome
owner:
  name:      Aidi Stan
  avatar:    avatar.jpg
  bio:       Valar Morghulis
  github:    aidistan

collections:
  notes:
    output: true
  convicts:
    output: false

# Jekyll
baseurl:     http://adome.aidistan.net
permalink:   pretty
timezone:    Asia/Shanghai
markdown:    kramdown
highlighter: pygments
include:     []
exclude:     ["README.md", "rakefile", "Gemfile"]

sass:
  style: :compressed

gems:
  - jekyll-sitemap

# Paginate
paginate:    10

# Duoshuo
duoshuo:     adome
duoshuo_url: http://adome.aidistan.net
