# Where things are
collections:
  notes:
    output:  true

# Handling reading
include:     []
exclude:     ["README.md", "Rakefile", "Gemfile", "CNAME"]

# Plugins
sass:
  style:     :compressed
gems:
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-paginate

# Conversion
markdown:    kramdown
highlighter: rouge

# Serving
baseurl:     http://blog.aiditan.me

# Outputting
permalink:   pretty
timezone:    Asia/Shanghai

# Templating
title:       Aidi's Blog
owner:       Aidi Stan
paginate:    10
duoshuo:     adome
duoshuo_url: http://blog.aiditan.me
