# Where things are
collections:
  posts_hided:
    output:  true
    permalink: /_/:name/

# Handling reading
include:     []
exclude:     ["README.md", "Rakefile", "Gemfile", "CNAME", "assets/vendor/amazeui/"]

# Plugins
sass:
  style:     :compressed
plugins:
  - jekyll-coffeescript
  - jekyll-feed

# Conversion
markdown:    kramdown
highlighter: rouge

# Serving
url:         https://blog.aidistan.site
baseurl:     ""

# Outputting
permalink:   pretty
timezone:    Asia/Shanghai

# Templating
title:       Aidi's Blog
author:      Aidi Tan
service:
  baidu:     true
