title:       Adome
owner:
  name:      Aidi Stan
  avatar:    avatar.jpg
  bio:       Valar Morghulis

collections:
  notes:
    output: true

# Jekyll
baseurl:     /adome
permalink:   pretty
timezone:    Asia/Shanghai
markdown:    kramdown
highlighter: pygments
include:     []
exclude:     ["README.md", "rakefile"]

# Paginate
paginate:    10

# Duoshuo
duoshuo:     adome
duoshuo_url: http://adome.aidistan.net
