title:             Adome
description:       "记录心情的点滴"
duoshuo_shortname: adome
duoshuo_url:       http://adome.aidistan.net
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:               

# Owner/author information
owner:
  name:            Aidi Stan
  avatar:          avatar.jpg
  bio:             Valar Morghulis

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   pretty

# Amount of post to show on home page
paginate: 10

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: []
exclude: ["README.md", "rakefile"]
