# Where things are
collections:
  notes:
    output:  true

# Handling reading
include:     []
exclude:     ["README.md", "Rakefile", "Gemfile", "CNAME"]

# Plugins
sass:
  style:     :compressed
gems:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Conversion
markdown:    kramdown
highlighter: rouge

# Serving
url:         http://blog.aidistan.site
baseurl:     ""

# Outputting
permalink:   pretty
timezone:    Asia/Shanghai

# Templating
title:       Aidi's Blog
author:      Aidi Tan
paginate:    20
service:
  baidu:     true
  uyan_uid:  1820817
