# Where things are
collections:
  notes:
    output:  true

# Handling reading
include:     []
exclude:     ["README.md", "Rakefile", "Gemfile", "CNAME"]

# Plugins
sass:
  style:     :compressed
gems:
  - jekyll-sitemap

# Conversion
markdown:    kramdown
highlighter: pygments

# Serving
baseurl:     http://adome.aidistan.net

# Outputting
permalink:   pretty
timezone:    Asia/Shanghai

# Templating
title:       Adome
owner:       Aidi Stan
paginate:    10
duoshuo:     adome
duoshuo_url: http://adome.aidistan.net
