# Where things are
collections:
  notes:
    output:  true
  posts_hided:
    output:  true
    permalink: /_/:name/

# Handling reading
include:     []
exclude:     ["README.md", "Rakefile", "Gemfile", "CNAME"]

# Plugins
sass:
  style:     :compressed
plugins:
  - jekyll-coffeescript

# Conversion
markdown:    kramdown
highlighter: rouge

# Serving
url:         http://blog.aidistan.site
baseurl:     ""

# Outputting
permalink:   pretty
timezone:    Asia/Shanghai

# Templating
title:       Aidi's Blog
author:      Aidi Tan
service:
  baidu:     true
