#
title:       Adome
permalink:   pretty
timezone:    Asia/Shanghai
url:         http://aidistan.github.io/adome

# Owner
owner:
  name:      Aidi Stan
  avatar:    avatar.jpg
  bio:       Valar Morghulis

# Paginate
paginate:    10

# Duoshuo
duoshuo:     adome
duoshuo_url: http://adome.aidistan.net

# 
markdown:    kramdown
highlighter: pygments
include:     []
exclude:     ["README.md", "rakefile"]
