# Basic infos
title: Aidi's Tech Blog
author:
  name: Aidi Tan
  email: aidistan@outlook.com
description: >-
  A journey of a thousand miles takes every step.
  「不积跬步无以至千里」
# header_pages:
#   - about.md
# show_excerpts: true

# 3rd-party services
google_analytics: G-P4N84HZ7FW
disqus:
  shortname: aidis-tech-blog

# Social links
minima:
  social_links:
    github: aidistan

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
